let arr=[1,2,3,4,4];
let newarrr = [...arr];
console.log(newarrr);
let str ='Bhavneet :';
let char = [...str];
console.log(char);
 const num1 = [1,3];
 const num3 = [2,5];
 const add = [...num1,...num3];
 console.log("This is how it look like after Shader");
 console.log(add);
